feat(install): add duf installer flow

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -2,19 +2,29 @@
 
 set -euo pipefail
 
-# shellcheck source=../lib/utils.bash
+# shellcheck source=lib/utils.bash
 source "$(dirname "$0")/../lib/utils.bash"
 
 mkdir -p "$ASDF_DOWNLOAD_PATH"
+platform=$(get_platform)
+ext=".tar.gz"
+if [ "$platform" == "windows" ]; then
+  ext=".zip"
+fi
 
-# TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION$ext"
 
 # Download tar.gz file to the download directory
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
-#  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+case $platform in
+  windows)
+    unzip "$release_file" -d "$ASDF_DOWNLOAD_PATH" || fail "Could not uncompress"
+    ;;
+  *)
+    tar zxvf "$release_file" -C "$ASDF_DOWNLOAD_PATH" >/dev/null || fail "Could not uncompress"
+    ;;
+esac
 
 # Remove the tar.gz file since we don't need to keep it
 rm "$release_file"
